FactoryBot.define do
  factory :ledger_webhook_endpoint, class: 'Ledger::WebhookEndpoint' do
    association :user
    url { 'https://example.com/webhooks' }
    active { true }
    event_types { [] }
    # secret is auto-generated by the before_validation callback
  end
end
